trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - 'azure-pipelines.yml'
      - README.md
      - '*.png'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Bicep
    displayName: 'Validating Bicep File'
    jobs:
      - job: ValidationJob
        displayName: 'Validating Bicep File'
        steps:
          - task: AzureCLI@2
            displayName: 'ValidationStep'
            inputs:
              